//
//  StringScheme.swift
//  Dyslire
//
//  Created by habachisirine on 22/11/2023.
//

import UIKit

struct StringConstants {
    static let kLblContinue: String = "Continue"
    static let k: String = ""
    static let kMsgMotDePasseOu: String = "Mot de passe oubliée ?"
    static let kMsgOtpVerificatio: String = "OTP Verification"
    static let kMsgVerifiezLeCod: String = "Verifiez le code recu sur votre Numero de téléphone :"
    static let kLblVRifier: String = "Vérifier"
    static let kLblCardiologue: String = "Cardiologue"
    static let kLblFri10: String = "Fri\n10"
    static let kLblSInscrire2: String = "s’inscrire"
    static let kLblSpCialitS: String = "Spécialités"
    static let kLblNeurologue: String = "Neurologue"
    static let kLblAboutMe: String = "About me"
    static let kLblSe: String = "Se "
    static let kLbl48: String = "4.8"
    static let kLblGeneral: String = "General"
    static let kMsgNouveauSurHea: String =
        "Nouveau sur Dyslire ? \nInscrivez-vous en un seul clic ."
    static let kMsgMakeAnAppoint: String = "Make An Appointment"
    static let kMsgRServezEtPla: String = "Ecole ou T'Existe"
    static let kLblSeeAll: String = "See All"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLblSeConnecter: String = "Se connecter"
    static let kLblActivités: String = "Activités"
    static let kLbl4279Reviews: String = "(4,279 reviews)"
    static let kLblMon06: String = "Mon\n06"
    static let kLblPDiatre: String = "Pédiatre"
    static let kLblConnecter: String = "connecter"
    static let kLblAvailableTime: String = "Available time"
    static let kLblPneumologue: String = "Pneumologue"
    static let kLblAnd: String = "and"
    static let kLblMDecins: String = "Médecins"
    static let kLbl0830Am: String = "08.30 AM"
    static let kLbl: String = "|"
    static let kMsgMondayFriday: String = "Monday - Friday, 08.00 AM - 20.00 PM"
    static let kLbl1100Am: String = "11.00 AM"
    static let kLblLink: String = "Link"
    static let kLblPlaceholder: String = "Placeholder"
    static let kMsgTermsConditi: String = "Terms & Conditions"
    static let kMsgRspadGatotSoe: String = "RSPAD Gatot Soebroto"
    static let kLblConsulter: String = "Consulter"
    static let kLblYourNumber: String = "Your number"
    static let kMsgPengalamanPrak: String = "Pengalaman Praktik"
    static let kMsgRsudGatotSubr: String = "RSUD Gatot Subroto"
    static let kLblEmail: String = "Email"
    static let Name: String = "Name"
    static let LastName: String = "Last Name"
    static let BirthDay: String = "Birth Date"
    static let kLblDrRandyWigham: String = "Dr Randy Wigham"
    static let kLblWorkingTime: String = "Working Time"
    static let kLblPrivacypolicy: String = "PrivacyPolicy."
    static let kMsgAppointmentTyp: String = "Appointment Type"
    static let kLbl1: String = "1"
    static let kLbl2: String = "2"
    static let kLbl3: String = "3"
    static let kLblSeConnecter2: String = "se connecter"
    static let kLbl0900Am: String = "09.00 AM"
    static let kLblInPerson: String = "In Person"
    static let kLblBibliothéques: String = "Bibliothéques"
    static let kMsgByLoggingYou2: String = "By logging, you agree to our"
    static let kLblOrSignInWith: String = "S'inscrire avec"
    static let kLblOrSignUpWith: String = "Se connecter avec"
  
    static let dyslire: String = "Dyslire"
    static let kLblSInscrire: String = "S’inscrire"
    static let kLblThu09: String = "Thu\n09"
    static let kLblSummary: String = "Summary"
    static let kLblWed08: String = "Wed\n08"
    static let kLblStr: String = "STR"
    static let kLbl2017Sekarang: String = "2017 - sekarang"
    static let kMsgVousAvezDJa: String =
        "Vous avez déja utilisé Dyslire ? \nConnectez-vous en un seul clic ."
    static let kLblHealth: String = "Health"
    static let kLblVideoCall: String = "Video Call"
    static let kLblDateTime: String = "Date & Time"
    static let kMsgDrJennyWatso: String =
        "Dr. Jenny Watson is the top most Immunologists specialist in Christ Hospital at London. She achived several awards for her wonderful contribution in medical field. She is available for private consultation."
    static let kLbl0930Am: String = "09.30 AM"
    static let kLblPayment: String = "Payment"
    static let kHttpFail: String = "HTTP request failed"
    static let kLblTue07: String = "Tue\n07"
    static let kLblSetManual: String = "Set Manual"
    static let kLbl4726482464: String = "4726482464"
    static let kLblProduits: String = "Produits"
    static let kLblGeneraliste: String = "Generaliste"
    static let kLblPassword: String = "Password"
    static let kMsgByLoggingYou: String =
        "By logging, you agree to our  Terms & Conditions and PrivacyPolicy."
    static let kLbl1000Am: String = "10.00 AM"
    static let kLbl0800Am: String = "08.00 AM"
    static let kLblPhoneCall: String = "Phone Call"
    static let kLblSelectDate: String = "Select Date"
    static let kMsgDrRandyWigha: String = "Dr. Randy Wigham"
    static let kLblDentiste: String = "Dentiste"
    static let kInvalidUrl: String = "Invalid URL"
    static let kLblRememberMe: String = "Remember me"
    static let kMsgBookAppointmen: String = "Book Appointment"
}

